Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,35 +38,35 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt 
 
-      # Runs a set of commands using the runners shell
-      - name: Pokreni_skriptu_za_csv
-        run: |
-          git fetch origin ${{ github.base_ref }}
+      # # Runs a set of commands using the runners shell
+      # - name: Pokreni_skriptu_za_csv
+      #   run: |
+      #     git fetch origin ${{ github.base_ref }}
 
-          BASE=${{ github.base_ref }}
+      #     BASE=${{ github.base_ref }}
 
-          files=$(git diff --name-only origin/$BASE...HEAD)
-          echo "Changed files:"
-          echo "$files"
+      #     files=$(git diff --name-only origin/$BASE...HEAD)
+      #     echo "Changed files:"
+      #     echo "$files"
           
-          has_csv=false
+      #     has_csv=false
           
-          for file in $files; do
-            if [[ "$file" == data/*.csv ]]; then
-              has_csv=true
-              echo "🔎 Validiram: $file"
-              python main.py "$file"
+      #     for file in $files; do
+      #       if [[ "$file" == data/*.csv ]]; then
+      #         has_csv=true
+      #         echo "🔎 Validiram: $file"
+      #         python main.py "$file"
           
-              if [ $? -ne 0 ]; then
-                echo "❌ FAIL: $file nije validan"
-                exit 1
-              fi
+      #         if [ $? -ne 0 ]; then
+      #           echo "❌ FAIL: $file nije validan"
+      #           exit 1
+      #         fi
           
-            else
-              echo "❌ NIJE DOZVOLJENO: $file"
-              exit 1
-            fi
-          done
+      #       else
+      #         echo "❌ NIJE DOZVOLJENO: $file"
+      #         exit 1
+      #       fi
+      #     done
           
-          echo "✅ OK"
+      #     echo "✅ OK"
   
